"""
Constants
"""

from _curses import ERR

CASH_START_COLUMN_DISPLAY = 50
LEVEL_START_COLUMN_DISPLAY = 8
SECOND_IN_MICROSECONDS = 1_000_000
NO_KEY_PRESSED = ERR
DATETIME_FORMAT = "%Y-%d-%m %H:%M:%S"
EMOJI_GRINNING_FACE = "😀"
EMOJI_GRINNING_FACE_BIG_EYES = "😃"
EMOJI_GRINNING_FACE_SMILING_EYES = "😄"
EMOJI_BEAMING_FACE_SMILING_EYES = "😁"
EMOJI_GRINNING_SQUINTING_FACE = "😆"
EMOJI_GRINNING_FACE_SWEAT = "😅"
EMOJI_CASH = "💵"
INFO_START_COLUMN_DISPLAY = 28
BUY_START_COLUMN_DISPLAY = 16
EXIT_KEY = "x"
CASH_IMAGE_MAX_DISPLAY = 10
EMOJI_ARROW_UP = "⬆"


FUTURE_INCOME_COLUMN_DISPLAY = 72
SAVE_GAME_FILE = "idle.save"
